### ISSUE TITLE
Useless variable scoping

### ISSUE THREAD

**Issue by KittyGiraudel** [cahnory/PlastiCSS#3]
Most of your scoped variables are prefixed by an underscore (e.g. `$_string`). Not only it is useless since it cannot conflict with anything outside the scope, but it also hurts readability.

**Comment by cahnory** [comment]
Function/mixin parameters cannot conflict but otherwise it seems to. I made an exemple here : http://codepen.io/anon/pen/knezm

Maybe I missed something ?

**Comment by KittyGiraudel** [comment]
Will be fixed in 3.3.

**Comment by cahnory** [comment]
Ok, I'll fix this when it'll be released.

**Comment by KittyGiraudel** [comment]
Time to fix.
